### ISSUE TITLE
Unable to produce Results for Pare

### ISSUE THREAD

**Issue by Benuraj** [fabioperez/transito-cv#3]
While trying to produce result for Pare detection m getting this
exception thrown!
An impossible set of object labels was detected. This is happening because none
of the object locations checked by the supplied image scanner is a close enough
match to one of the truth boxes. To resolve this you need to either lower the 
match_eps or adjust the settings of the image scanner so that it hits this 
truth box. Or you could adjust the offending truth rectangle so it can be 
matched by the current image scanner. Also, if you are using the 
scan_image_pyramid object then you could try using a finer image pyramid or 
adding more detection templates. E.g. if one of your existing detection 
templates has a matching width/height ratio and smaller area than the offending
rectangle then a finer image pyramid would probably help.

Any suggestion how to proceed?

**Comment by fabioperez** [comment]
Can you provide more details like what commands you executed?

I just tested the detection for `examples/images/pare.jpg` and I got the expected results:

    build/detect -u1 --wait examples/images/pare.jpg

**Comment by Benuraj** [comment]
Yeah I think I figured out the problem. The reason probably is this, while tagging train and test data the pare symbols all included small signs as well, and when I looked inside the code Window_Size parameter is set as 80 x 80 in default. I guess reason is that. Is there any plan to make this work for any window size (I mean user provided filter size)?

Thanks for the help.

**Comment by fabioperez** [comment]
Currently, I have no plans to update this project, but feel free to send a pull-request.
